name = "Kablet"
client_id = "468a9b31e9ad02a319dbc3b88d6b4039"
application_url = "https://kablet-backend.onrender.com/app"
embedded = true

[access_scopes]
scopes = "read_orders,write_orders,read_draft_orders,write_draft_orders,read_products"

[auth]
redirect_urls = ["https://kablet-backend.onrender.com/auth/callback"]

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  topics = ["customers/data_request"]
  uri = "/webhooks/customers/data_request"

  [[webhooks.subscriptions]]
  topics = ["customers/redact"]
  uri = "/webhooks/customers/redact"

  [[webhooks.subscriptions]]
  topics = ["shop/redact"]
  uri = "/webhooks/shop/redact"

[pos]
embedded = false