client_id = "67a720f66e77c1e3f597ddef97dbde0e"
name = "Kablet"
application_url = "https://kablet-backend.onrender.com/app"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-07"

[access.admin]
direct_api_mode = "offline"

[access_scopes]
scopes = "read_orders,write_orders,read_draft_orders,write_draft_orders,read_customers"
use_legacy_install_flow = true

[auth]
redirect_urls = [ "https://kablet-backend.onrender.com/auth/callback" ]