import { useState, useEffect } from 'preact/hooks'
import { dashboardApi, fmtAmount, fmtDate, decisionLabel } from '../../../../../shared/models/dashboard.ts'

const PERIODS = [
  { label: 'Today',    value: 'today' },
  { label: '7 days',  value: '7d' },
  { label: '30 days', value: '30d' },
  { label: 'All time', value: 'lifetime' },
]

function instanceTone(state) {
  switch (state) {
    case 'COMPLETED': return 'success'
    case 'ACCEPTED':  return 'info'
    case 'DECLINED':  return 'neutral'
    case 'EXPIRED':   return 'neutral'
    case 'FAILED':    return 'critical'
    default:          return 'attention'
  }
}

function instanceLabel(state) {
  return state.charAt(0) + state.slice(1).toLowerCase()
}

/** @param {{ token: string }} props */
export default function DashboardPage({ token }) {
  const [period, setPeriod] = useState('lifetime')
  const [summary, setSummary] = useState(null)
  const [transactions, setTransactions] = useState([])
  const [total, setTotal] = useState(0)
  const [page, setPage] = useState(1)
  const [config, setConfig] = useState(null)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState(null)

  const load = async (p, pg = 1) => {
    setLoading(true)
    setError(null)
    try {
      const [s, t, c] = await Promise.all([
        dashboardApi.getSummary(token, p),
        dashboardApi.getTransactions(token, pg, p),
        config === null ? dashboardApi.getConfig(token) : Promise.resolve(config),
      ])
      setSummary(s)
      setTransactions(t.transactions)
      setTotal(t.total)
      setPage(pg)
      if (config === null) setConfig(c)
    } catch (e) {
      setError('Failed to load dashboard data. Please try again.')
    }
    setLoading(false)
  }

  useEffect(() => { load(period) }, [])

  const handlePeriod = (p) => {
    setPeriod(p)
    load(p, 1)
  }

  const totalPages = Math.ceil(total / 20)

  return (
    <s-page heading="Kablet Dashboard">

      {/* Engine status badge */}
      {config && (
        <s-badge slot="primary-action" tone={config.engine_enabled ? 'success' : 'critical'}>
          Engine {config.engine_enabled ? 'Active' : 'Paused'}
        </s-badge>
      )}

      {error && (
        <s-section>
          <s-banner tone="critical">
            <s-paragraph>{error}</s-paragraph>
          </s-banner>
        </s-section>
      )}

      {/* Period selector */}
      <s-section heading="Time Period">
        <s-segmented-control>
          {PERIODS.map(p => (
            <s-segmented-control-item
              key={p.value}
              selected={period === p.value}
              onClick={() => handlePeriod(p.value)}
            >
              {p.label}
            </s-segmented-control-item>
          ))}
        </s-segmented-control>
      </s-section>

      {/* KPI cards */}
      <s-section heading="Revenue Overview">
        {loading && !summary ? (
          <s-stack direction="inline" gap="base" alignItems="center">
            <s-spinner />
            <s-text>Loading…</s-text>
          </s-stack>
        ) : summary ? (
          <s-grid columns="3" gap="base">
            <s-card>
              <s-box paddingBlock="base" paddingInline="base">
                <s-stack gap="tight">
                  <s-text tone="subdued" size="small">Additional Revenue</s-text>
                  <s-text size="large" fontWeight="bold">
                    {fmtAmount(summary.total_revenue)}
                  </s-text>
                  <s-text tone="subdued" size="small">Generated by Kablet</s-text>
                </s-stack>
              </s-box>
            </s-card>

            <s-card>
              <s-box paddingBlock="base" paddingInline="base">
                <s-stack gap="tight">
                  <s-text tone="subdued" size="small">Revenue Per Order</s-text>
                  <s-text size="large" fontWeight="bold">
                    {fmtAmount(summary.revenue_per_order)}
                  </s-text>
                  <s-text tone="subdued" size="small">Average uplift per transaction</s-text>
                </s-stack>
              </s-box>
            </s-card>

            <s-card>
              <s-box paddingBlock="base" paddingInline="base">
                <s-stack gap="tight">
                  <s-text tone="subdued" size="small">Acceptance Rate</s-text>
                  <s-text size="large" fontWeight="bold">{summary.acceptance_rate}%</s-text>
                  <s-text tone="subdued" size="small">Customers who accepted</s-text>
                </s-stack>
              </s-box>
            </s-card>

            <s-card>
              <s-box paddingBlock="base" paddingInline="base">
                <s-stack gap="tight">
                  <s-text tone="subdued" size="small">Transactions Processed</s-text>
                  <s-text size="large" fontWeight="bold">
                    {summary.transactions_processed.toLocaleString()}
                  </s-text>
                  <s-text tone="subdued" size="small">Orders analyzed</s-text>
                </s-stack>
              </s-box>
            </s-card>

            <s-card>
              <s-box paddingBlock="base" paddingInline="base">
                <s-stack gap="tight">
                  <s-text tone="subdued" size="small">Opportunities Presented</s-text>
                  <s-text size="large" fontWeight="bold">
                    {summary.opportunities_presented.toLocaleString()}
                  </s-text>
                  <s-text tone="subdued" size="small">Shown to customers</s-text>
                </s-stack>
              </s-box>
            </s-card>

            <s-card>
              <s-box paddingBlock="base" paddingInline="base">
                <s-stack gap="tight">
                  <s-text tone="subdued" size="small">Opportunities Accepted</s-text>
                  <s-text size="large" fontWeight="bold">
                    {summary.opportunities_accepted.toLocaleString()}
                  </s-text>
                  <s-text tone="subdued" size="small">Converted by customers</s-text>
                </s-stack>
              </s-box>
            </s-card>
          </s-grid>
        ) : null}
      </s-section>

      {/* Transactions table */}
      <s-section heading={`Recent Transactions${total > 0 ? ` · ${total.toLocaleString()} total` : ''}`}>
        {loading ? (
          <s-stack direction="inline" gap="base" alignItems="center">
            <s-spinner />
            <s-text>Loading transactions…</s-text>
          </s-stack>
        ) : transactions.length === 0 ? (
          <s-stack gap="base" alignItems="center">
            <s-paragraph>No transactions yet for this period.</s-paragraph>
            <s-paragraph tone="subdued">
              Transactions will appear here once your first order is processed.
            </s-paragraph>
          </s-stack>
        ) : (
          <>
            <s-table>
              <s-table-header-row>
                <s-table-header>Date</s-table-header>
                <s-table-header>Order</s-table-header>
                <s-table-header>Order Value</s-table-header>
                <s-table-header>Opportunity</s-table-header>
                <s-table-header>Decision</s-table-header>
                <s-table-header>Revenue</s-table-header>
                <s-table-header>Status</s-table-header>
              </s-table-header-row>
              <s-table-body>
                {transactions.map(tx => (
                  <s-table-row key={tx.id}>
                    <s-table-cell>{fmtDate(tx.received_at)}</s-table-cell>
                    <s-table-cell>
                      <s-text tone="subdued">#{tx.shopify_order_id}</s-text>
                    </s-table-cell>
                    <s-table-cell>
                      <s-text fontWeight="semibold">
                        {fmtAmount(tx.transaction_value, tx.transaction_currency)}
                      </s-text>
                    </s-table-cell>
                    <s-table-cell>
                      {tx.offer_name
                        ? <s-text>{tx.offer_name}</s-text>
                        : <s-text tone="subdued">—</s-text>}
                    </s-table-cell>
                    <s-table-cell>
                      <s-text tone="subdued">
                        {decisionLabel(tx.decision?.outcome_type)}
                      </s-text>
                    </s-table-cell>
                    <s-table-cell>
                      {tx.instance?.outcome_value
                        ? <s-text tone="success" fontWeight="semibold">
                            {fmtAmount(tx.instance.outcome_value)}
                          </s-text>
                        : <s-text tone="subdued">—</s-text>}
                    </s-table-cell>
                    <s-table-cell>
                      {tx.instance
                        ? <s-badge tone={instanceTone(tx.instance.current_state)}>
                            {instanceLabel(tx.instance.current_state)}
                          </s-badge>
                        : <s-text tone="subdued">—</s-text>}
                    </s-table-cell>
                  </s-table-row>
                ))}
              </s-table-body>
            </s-table>

            {/* Pagination */}
            {totalPages > 1 && (
              <s-stack direction="inline" gap="base" alignItems="center">
                <s-button
                  disabled={page <= 1 || loading}
                  onClick={() => load(period, page - 1)}
                >
                  ← Previous
                </s-button>
                <s-text tone="subdued">Page {page} of {totalPages}</s-text>
                <s-button
                  disabled={page >= totalPages || loading}
                  onClick={() => load(period, page + 1)}
                >
                  Next →
                </s-button>
              </s-stack>
            )}
          </>
        )}
      </s-section>

      {/* Engine info callout */}
      <s-section>
        <s-banner tone="info">
          <s-heading>Decision Engine is running automatically</s-heading>
          <s-paragraph>
            Kablet analyzes every transaction and selects the highest-converting opportunity for each customer. No manual configuration needed.
          </s-paragraph>
        </s-banner>
      </s-section>

    </s-page>
  )
}
